# Generated by Django 5.1.4 on 2024-12-23 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '000X_create_staff_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age_at_arrival',
            field=models.IntegerField(verbose_name='Age at Arrival (in months)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='arrival_date',
            field=models.DateField(verbose_name='Arrival Date'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.breed', verbose_name='Breed'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='inventory_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Inventory Number'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.animal', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='weighting',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.animal', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='weighting',
            name='date',
            field=models.DateField(verbose_name='Date of Weighting'),
        ),
        migrations.AlterField(
            model_name='weighting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='weighting',
            name='weight',
            field=models.FloatField(default=0.0, verbose_name='Weight'),
        ),
    ]
